  <produit><!-- Debut Produit -->
    <nom> TITRE </nom>
    <prix monnaie="Euros" > 50 </prix>
    <quantite>5</quantite>
  </produit><!-- Fin Produit -->
  <produit>
  <nom> CD </nom>
 </produit>
 <fournisseur>
   <nom>Fnac</nom>
   <description>
      <adresse>Aix en Provence</adresse>
      <telephone>0000000000</telephone>
      <rue><![CDATA[en HTML, la balise<p> est très utile !]]>&#169; J.-L.&#160;Massat
</rue>
   </description>
</fournisseur>
