//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.13 at 10:44:25 PM CET 
//


package javax.src.monpkg;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nom",
    "numero",
    "numeroSemaine",
    "numeroAnnee",
    "personne"
})
@XmlRootElement(name = "jour")
public class Jour {

    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;
    @XmlAttribute(name = "suivant", required = true)
    @XmlIDREF
    protected Object suivant;
    @XmlElement(required = true)
    protected String nom;
    @XmlElement(required = true)
    protected String numero;
    @XmlElement(name = "numero-semaine", required = true)
    protected String numeroSemaine;
    @XmlElement(name = "numero-annee", required = true)
    protected String numeroAnnee;
    protected String personne;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the suivant property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getSuivant() {
        return suivant;
    }

    /**
     * Sets the value of the suivant property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setSuivant(Object value) {
        this.suivant = value;
    }

    /**
     * Gets the value of the nom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNom() {
        return nom;
    }

    /**
     * Sets the value of the nom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNom(String value) {
        this.nom = value;
    }

    /**
     * Gets the value of the numero property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumero() {
        return numero;
    }

    /**
     * Sets the value of the numero property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumero(String value) {
        this.numero = value;
    }

    /**
     * Gets the value of the numeroSemaine property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroSemaine() {
        return numeroSemaine;
    }

    /**
     * Sets the value of the numeroSemaine property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroSemaine(String value) {
        this.numeroSemaine = value;
    }

    /**
     * Gets the value of the numeroAnnee property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroAnnee() {
        return numeroAnnee;
    }

    /**
     * Sets the value of the numeroAnnee property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroAnnee(String value) {
        this.numeroAnnee = value;
    }

    /**
     * Gets the value of the personne property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonne() {
        return personne;
    }

    /**
     * Sets the value of the personne property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonne(String value) {
        this.personne = value;
    }

}
