CC=gcc
CFLAGS= -Wall -ansi -pedantic -std=c99
LDFLAGS=
EXEC=decoupe

all: glouton1 glouton2 exec

glouton1:
	gcc glouton1.c -std=c99 -o glouton1

glouton2:
	gcc glouton2.c -std=c99 -o glouton2

exec:
	./glouton1 B1.1

